title: 'VMG-metall'
default_lang: ru
author:
  name: ''
  email: 'ivan160881@mail.ru'
taxonomies:
  - category
  - tag
metadata:
  description: ''
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /catalog
s_phone: '+7 (916) 112-00-33'
s_address: 'Московская обл. г.Балашиха, ул.Пехра-Покровская, д.8А'
